# Generated by Django 2.2.5 on 2019-11-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default='', max_length=32)),
                ('number_of_entry', models.IntegerField(default=-1)),
                ('city', models.CharField(default='', max_length=64)),
                ('field', models.CharField(default='', max_length=64)),
                ('department', models.CharField(default='', max_length=64)),
                ('wechatid', models.CharField(default='', max_length=64)),
                ('tel', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=64)),
                ('self_discription', models.CharField(default='', max_length=600)),
                ('company', models.CharField(default='', max_length=100)),
                ('hobby', models.CharField(default='', max_length=100)),
                ('avatar_url', models.CharField(default='/media/user_avatar/default/default.jpg', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('openid', models.CharField(max_length=32, unique=True)),
                ('session_key', models.CharField(default='', max_length=32)),
                ('logon_status', models.IntegerField(default=-1)),
                ('info', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='UserSystem.UserInfo')),
            ],
        ),
    ]
