# Generated by Django 2.2.5 on 2019-12-17 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True, unique=True)),
                ('student_list_id', models.TextField(default='')),
                ('advisor_list_id', models.TextField(default='')),
                ('student_list_name', models.TextField(default='')),
                ('advisor_list_name', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default='', max_length=32)),
                ('number_of_entry', models.CharField(default='', max_length=32)),
                ('city', models.CharField(default='', max_length=64)),
                ('field', models.CharField(default='', max_length=64)),
                ('department', models.CharField(default='', max_length=64)),
                ('wechatid', models.CharField(default='', max_length=64)),
                ('tel', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=64)),
                ('self_discription', models.CharField(default='', max_length=600)),
                ('company', models.CharField(default='', max_length=100)),
                ('hobby', models.CharField(default='', max_length=100)),
                ('avatar_url', models.CharField(default='/media/user_avatar/default/default.jpg', max_length=100)),
                ('is_connected', models.IntegerField(default=0)),
                ('is_in_group', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=32, null=True, unique=True)),
                ('session_key', models.CharField(default='', max_length=32)),
                ('logon_status', models.IntegerField(default=-1)),
                ('info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserSystem.UserInfo')),
            ],
        ),
    ]
