# Generated by Django 2.2.5 on 2019-10-11 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('openid', models.CharField(max_length=32, unique=True)),
                ('logon_status', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2019, 10, 11, 3, 27, 25, 985096, tzinfo=utc))),
            ],
        ),
    ]
