# Generated by Django 2.2.5 on 2019-11-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='number_of_entry',
            field=models.CharField(default='', max_length=32),
        ),
    ]
