# Generated by Django 2.2.5 on 2019-11-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSystem', '0002_auto_20191116_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
