# Generated by Django 2.2.5 on 2019-11-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSystem', '0005_auto_20191116_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_connected',
            field=models.IntegerField(default=0),
        ),
    ]
