# Generated by Django 2.2.7 on 2019-11-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('openid', models.CharField(max_length=32, null=True, unique=True)),
                ('session_key', models.CharField(default='', max_length=32)),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=99999)),
                ('due', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-c_time'],
            },
        ),
    ]
