# Generated by Django 2.2.5 on 2019-11-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceSystem', '0002_remove_resource_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='openid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
