# Generated by Django 2.2.5 on 2019-12-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceSystem', '0003_auto_20191121_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='img_arr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
