# Generated by Django 2.2.5 on 2019-12-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceSystem', '0004_auto_20191201_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
