# Generated by Django 2.2.5 on 2019-12-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceSystem', '0005_resource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='tag_arr',
            field=models.TextField(default=''),
        ),
    ]
