# Generated by Django 2.2.5 on 2019-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceSystem', '0006_auto_20191201_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cover_img',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
