# Generated by Django 2.2.5 on 2019-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceSystem', '0007_resource_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='interest_users',
            field=models.TextField(default=''),
        ),
    ]
